//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guestbook.API
{
    using System;
    using System.Collections.Generic;
    using Models;

    public partial class Entry
    {
        public int EntryId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Name { get; set; }
        public string EntryContent { get; set; }

        internal void Update(EntriesModel entry)
        {
           if(EntryId == 0)
            {
                CreatedDate = DateTime.Now;
            }
            Name = entry.Name;

            EntryContent = entry.EntryContent;
        }
    }
}
